image: debian:buster

build:
  script:
  - apt update
  - apt install -y sudo make
  - make install_buildenv
  - sudo sed -i '1161s%umount%#umount%' /usr/share/debootstrap/functions
  - sudo mount -o remount,dev /builds
  - make
  variables:
    DEBIAN_FRONTEND: "noninteractive"
  cache:
    paths:
      - cache/
  interruptible: true
