name: Send notification on workflow status

on:
  workflow_run:
    workflows:
      - CI

jobs:
  alert:
    runs-on: ubuntu-latest
    steps:
      - name: Send Alert
        run: |
          curl -d "ISO Build pipeline finished, status: ${{ github.event.workflow_run.conclusion }}" -H "T: Debian ISO Workflow" ${{ secrets.notification }}

# https://docs.github.com/en/webhooks/webhook-events-and-payloads#workflow_run